---
- hosts: all
  gather_facts: no
  tasks:

  - debug:
      var: hostvars[inventory_hostname]
      

- hosts: all
  gather_facts: yes
  tasks:

  - debug:
      var: hostvars[inventory_hostname]
 - debug: var=ansible_distribution
