---
- hosts: all
  gather_facts: no
  tasks:

  - debug:
      var: hostvars[inventory_hostname]
      

- hosts: all
  gather_facts: yes
  tasks:

  - debug:
      var: hostvars[inventory_hostname]
      var: ansible_distribution
      var: ansible_all_ipv4_addresses
      var: ansible_hostname
