- name: perform yum update / reboot server
  hosts: all
 
  tasks:
        - name: Perform yum update of all packages
          yum:
            name: '*'
            state: latest
        - name: Reboot machine
          reboot:
