---
# performYumUpdateRebootServer.yml
# performs yum update and reboots server
- name: perform yum update / reboot server
  hosts: all
  remote_user: root
  #become: true
  #become_method: sudo
  #become_user: root
 
  tasks:
        - name: Perform yum update of all packages
          yum:
            name: '*'
            state: latest
            
        - name: restart system to reboot to newest kernel
          shell: "sleep 5 && reboot"
          async: 1
          poll: 0

       # - name: wait for 10 seconds
        #  pause:
         # seconds: 10

        - name: wait for the system to reboot
          wait_for_connection:
          connect_timeout: 20
          sleep: 5
          delay: 5
          timeout: 60

      - name: install epel-release
          yum:
          name: epel-release
          state: latest
