---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html

  hosts: all
  gather_facts: true  
 
 - name: Collect only facts returned by facter
 
  tasks:
 #   - debug: var=vars
 #   - debug: var=hostvars[inventory_hostname]
 
    setup:
      gather_subset:
      - '!all'
      - '!any'
      - facter
