---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html

- name:  Windows Update
  hosts: all
  gather_facts: true
  tasks:
    - name: Install Firefox
      win_chocolatey:
        name: 
        - firefox
        - procexp
        - windirstat
        - javaruntime
        - googlechrome
        - vcredist140
        - autohotkey.portable
        - ccleaner
        - winlogbeat
        - malwarebytes
        - autoruns
        - keepass.install
        - wsus-offline-update
        state: present
        
    - name: ensure mobatek is installed via win_package
      win_get_url:
        url: https://download.mobatek.net/1242019111120613/MobaXterm_Installer_v12.4.zip
        dest: C:\
    
    - name: Unarchives the zip file
      unarchive:
        src: C:\MobaXterm_Installer_v12.4.zip
        dest: /temp
    
    - name: mobatek the zip file 
      win_package:
        path: C:\temp\MobaXterm_installer_12.4.msi
        state: present
  
