---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html

- name:  Windows Update
  hosts: all
  gather_facts: false
  tasks:
    - name: Install Firefox
      win_chocolatey:
        name: firefox
        state: present
 
- name: Install multiple packages
  win_chocolatey:
    name:
    - procexp
    - putty
    - windirstat
    state: present
