---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html

- name:  Windows Update
  hosts: all
  gather_facts: true
  tasks:
    - name: install windows feature AD-DS on DCs
    win_feature:
      name: AD-Domain-Services
      state: present
      include_management_tools: yes
      include_sub_features: yes
    when: ansible_facts.memtotal_mb == 4096
    register: adds_install
    
    - name: Install Firefox
      win_chocolatey:
        name: 
        - firefox
        - procexp
        - windirstat
        - javaruntime
        - googlechrome
        - vcredist140
        - autohotkey.portable
        - ccleaner
        - winlogbeat
        - malwarebytes
        - autoruns
        - keepass.install
        - wsus-offline-update
        state: present
 

