---
# Ansible playbook to run Windows Update and restart, if required
#
# http://docs.ansible.com/ansible/win_updates_module.html
# https://docs.ansible.com/ansible/win_reboot_module.html

- name:  Windows Update
  hosts: all
  gather_facts: true  
  
  tasks:
    - debug: var=vars
    - debug: var=hostvars[inventory_hostname]
  
- name: Printing Facts Mate?
      setup:
      gather_subset: 'all'
